### Top Level Base Image (Alpine)
### Dave Conroy <github.com/tiredofit>

name: "manual_build_image"

on:
  workflow_dispatch:
    inputs:
      Manual Build:
        description: 'Manual Build'
        required: false

